---
title: "Rough Sketch"
author: "Brad Stieber"
date: "March 5, 2017"
output: pdf_document
classoption: landscape
---
```{r echo = FALSE, warning=FALSE, message=FALSE}
suppress <- TRUE

if(suppress){
  suppressPackageStartupMessages(source('prepdata.R'))  
}else{
  source('prepdata.R')
}



pm_label <- function(log2 = FALSE){
  if(log2){
    expression(paste('3 Day Rolling Average of  ',
                     PM[2.5],'  Concentration (',
                     log[2], ' scale)'))
  }else{
    expression(paste('3 Day Rolling Average of  ',
                     PM[2.5],'  Concentration'))
  }
}

# longer time series plot using rolling average

ggplot(air_q_all.byday, aes(x = Date, y = RollingAvgPollution))+
  geom_point()+
  ylab(pm_label())+
  ggtitle(expression(
    paste('Beijing Air Quality: Daily ',
          PM[2.5],
          ' Concentration')),
    subtitle = expression(
      paste(
        PM[2.5], ' concentration measured in ',
        mu, 'g/', m^3
      )
    ))

# add weekday and season to data
air_q_all.byday <- air_q_all.byday %>%
  mutate(DayOfWeek = weekdays(Date),
         Season = ifelse(Month %in% c(12,1,2), 'Winter',
                         ifelse(Month %in% 3:5, 'Spring',
                                ifelse(Month %in% 6:8, 'Summer','Fall')))
         ) %>%
  mutate(DayOfWeek = factor(DayOfWeek, 
                            levels = c('Saturday','Sunday',
                                       'Monday','Tuesday',
                                       'Wednesday','Thursday',
                                       'Friday')),
         Season = factor(Season,
                         levels = c('Spring','Summer',
                                    'Fall','Winter')))


```

Sketch 1:

```{r echo = FALSE, message = FALSE, warning=FALSE}
#story 1
# does it being a work week affect pollution?
# 
ggplot(data = air_q_all.byday,
       aes(x = DayOfWeek, y = MedPollution))+
  geom_point(data = jitter_sum,
              aes(x = DayOfWeek, y = MedPollution),
              pch = 1,
               alpha = .5)+
  geom_errorbar(data = error_bar_sum,
                aes(x = DayOfWeek,
                    ymin = Lower50Med,
                    ymax = Upper50Med),
                size = 1.2, inherit.aes = FALSE)+
  geom_errorbar(data = error_bar_sum,
                aes(x = DayOfWeek,
                    ymin = Lower90Med,
                    ymax = Upper90Med),
                size = 1.2, linetype = 'dashed',
                inherit.aes = FALSE)+
  stat_summary(fun.y = 'median', geom = 'point', colour = '#b70101',
               size = 4)+
  facet_wrap(~Season, nrow = 1)+
  scale_y_continuous(trans = log_trans(2),
                     name = expression(paste('Median ', PM[2.5],
                                             ' Concentration (',
                                             log[2], ' scale)')))+
  xlab('')+
  scale_x_discrete(labels = c('Sunday' = 'Sun',
                              'Monday' = 'Mon',
                              'Tuesday' = 'Tue',
                              'Wednesday' = 'Wed',
                              'Thursday' = 'Thu',
                              'Friday' = 'Fri',
                              'Saturday' = 'Sat'))+
  ggtitle('Median PM2.5 Concentration by Day of Week and Season',
          subtitle = 'Data for 2011 - 2016, y-axis is log-scaled')


```

Sketch 2

```{r echo = FALSE, message = FALSE, warning=FALSE}
#manually generate a paired scatter plot
library(gridExtra)
library(GGally)

cor_table <- air_q_all.byday %>%
  group_by(Season) %>%
  summarise(CorPolHum = cor(log2(RollingAvgPollution), MeanHumid_RollingAvg,
                            use = 'pairwise'),
            CorPolWS = cor(log2(RollingAvgPollution), log2(MeanWindSpeed_RollingAvg),
                           use = 'pairwise'),
            CorPolTemp = cor(log2(RollingAvgPollution), MeanTempF_RollingAvg,
                             use = 'pairwise'))

p02 <- ggplot(cor_table,
              aes(x = 1, y = Season, 
                  label = 
                    paste0(Season, ': ', round(CorPolHum,2))))+
  geom_text(aes(colour = Season), size = 6)+
  # geom_text(aes(x = 1, y = 4.25, 
  #               label = 'Correlations between\nlog2(Pollution) and Humidity:'), 
  #           size = 4, inherit.aes = FALSE)+
  scale_colour_brewer(palette = 'Set1')+
  theme(axis.ticks = element_blank(),
        axis.text = element_blank(),
        panel.grid = element_blank())

p03 <- ggplot(cor_table,
              aes(x = 1, y = Season, 
                  label = 
                    paste0(Season, ': ', round(CorPolWS,2))))+
  geom_text(aes(colour = Season), size = 6)+
  # geom_text(aes(x = 1, y = 4.25, 
  #               label = 'Correlations between log2(Pollution) and log2(Wind Speed):'), 
  #           size = 6, inherit.aes = FALSE)+
  scale_colour_brewer(palette = 'Set1')+
  theme(axis.ticks = element_blank(),
        axis.text = element_blank(),
        panel.grid = element_blank())

p04 <- ggplot(cor_table,
              aes(x = 1, y = Season, 
                  label = 
                    paste0(Season, ': ', round(CorPolTemp,2))))+
  geom_text(aes(colour = Season), size = 6)+
  # geom_text(aes(x = 1, y = 4.25, 
  #               label = 'Correlations between log2(Pollution) and Temperature:'), 
  #           size = 6, inherit.aes = FALSE)+
  scale_colour_brewer(palette = 'Set1')+
  theme(axis.ticks = element_blank(),
        axis.text = element_blank(),
        panel.grid = element_blank())

#histogram
p01 <- ggplot(air_q_all.byday, aes(x = RollingAvgPollution))+
  geom_histogram(fill = 'grey60', colour = 'black',
                 bins = 50)+
  scale_x_continuous(trans = log_trans(2))+
  theme(axis.text = element_blank(),
        axis.ticks = element_blank())

p12 <- ggplot(air_q_all.byday, aes(x = MeanHumid_RollingAvg))+
  geom_histogram(fill = 'grey60', colour = 'black')

p23 <- ggplot(air_q_all.byday, aes(x = MeanWindSpeed_RollingAvg))+
  geom_histogram(fill = 'grey60', colour = 'black')+
  scale_x_continuous(trans = log_trans(2))

p34 <- ggplot(air_q_all.byday, aes(x = MeanTempF_RollingAvg))+
  geom_histogram(fill = 'grey60', colour = 'black')


#pollution on x axis (column 1, rows 1-3)
p11 <- ggplot(air_q_all.byday, aes(x = RollingAvgPollution, y = MeanHumid_RollingAvg))+
  geom_point(aes(colour = Season), pch = 1, alpha = .8)+
  scale_color_brewer(palette = 'Set1')+
  scale_x_continuous(trans = log_trans(2))+
  guides(colour = guide_legend(override.aes = list(size = 3, alpha = 1, pch = 15)))

p21  <- ggplot(air_q_all.byday, aes(x = RollingAvgPollution, 
                                    y = MeanWindSpeed_RollingAvg))+
  geom_point(aes(colour = Season), pch = 1, alpha = .8)+
  scale_color_brewer(palette = 'Set1')+
  scale_x_continuous(trans = log_trans(2))+
  scale_y_continuous(trans = log_trans(2))

p31 <- ggplot(air_q_all.byday, aes(x = RollingAvgPollution, y = MeanTempF_RollingAvg))+
  geom_point(aes(colour = Season), pch = 1, alpha = .8)+
  scale_color_brewer(palette = 'Set1')+
  scale_x_continuous(trans = log_trans(2))


#humidity on x axis, (column 2, rows0, 2, 3)

# p02 <- ggplot(air_q_all.byday, aes(y = RollingAvgPollution, x = MeanHumid_RollingAvg))+
#   geom_point(aes(colour = Season), pch = 1, alpha = .8)+
#   scale_color_brewer(palette = 'Set1')+
#   scale_y_continuous(trans = log_trans(2))+
#   guides(colour = guide_legend(override.aes = list(size = 3, alpha = 1, pch = 15)))

p22 <- ggplot(air_q_all.byday, aes(x = MeanHumid_RollingAvg, 
                                   y = MeanWindSpeed_RollingAvg))+
  geom_point(aes(colour = Season), pch = 1, alpha = .8)+
  scale_color_brewer(palette = 'Set1')+
  scale_y_continuous(trans = log_trans(2))


p32 <- ggplot(air_q_all.byday, aes(x = MeanHumid_RollingAvg, y = MeanTempF_RollingAvg))+
  geom_point(aes(colour = Season), pch = 1, alpha = .8)+
  scale_color_brewer(palette = 'Set1')


# wind speed on x axis(column 3, rows 0,1,3)

# p03 <- ggplot(air_q_all.byday, aes(y = RollingAvgPollution, 
#                                    x = MeanWindSpeed_RollingAvg))+
#   geom_point(aes(colour = Season), pch = 1, alpha = .8)+
#   scale_color_brewer(palette = 'Set1')+
#   scale_x_continuous(trans = log_trans(2))+
#   scale_y_continuous(trans = log_trans(2))

p13 <- ggplot(air_q_all.byday, aes(x = MeanWindSpeed_RollingAvg, 
                                   y = MeanHumid_RollingAvg))+
  geom_point(aes(colour = Season), pch = 1, alpha = .8)+
  scale_color_brewer(palette = 'Set1')+
  scale_x_continuous(trans = log_trans(2))

p33 <- ggplot(air_q_all.byday, aes(x = MeanWindSpeed_RollingAvg, 
                                   y = MeanTempF_RollingAvg))+
  geom_point(aes(colour = Season), pch = 1, alpha = .8)+
  scale_color_brewer(palette = 'Set1')+
  scale_x_continuous(trans = log_trans(2))

#temp on x axis (column 4, rows 0 - 3)

# p04 <- ggplot(air_q_all.byday, aes(y = RollingAvgPollution, 
#                                    x = MeanTempF_RollingAvg))+
#   geom_point(aes(colour = Season), pch = 1, alpha = .8)+
#   scale_color_brewer(palette = 'Set1')+
#   scale_y_continuous(trans = log_trans(2))
# 


p14 <- ggplot(air_q_all.byday, aes(y = MeanHumid_RollingAvg, 
                                   x = MeanTempF_RollingAvg))+
  geom_point(aes(colour = Season), pch = 1, alpha = .8)+
  scale_color_brewer(palette = 'Set1')

p24 <- ggplot(air_q_all.byday, aes(y = MeanWindSpeed_RollingAvg, x = MeanTempF_RollingAvg))+
  geom_point(aes(colour = Season), pch = 1, alpha = .8)+
  scale_color_brewer(palette = 'Set1')+
  scale_y_continuous(trans = log_trans(2))



ggmatrix(list(
  p01,
 # p02, NULL, NULL,
  p02, p03, p04,
  p11, p12, p13, p14,
  p21, p22, p23, p24,
  p31, p32, p33, p34
), nrow = 4, ncol = 4, legend = c(2,1), showStrips = TRUE,
xAxisLabels = 
  c('Pollution [PM2.5] (log base 2)',
    'Humidiity [%]',
    'Wind Speed [MPH] (log base 2)',
    'Temperature [F]'
  ))+
  theme(legend.position = 'top',
        legend.title = element_text(size = 14),
        legend.text = element_text(size = 12))




```

